

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "^1.0.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "^2.1.1"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.1.0"
